version: '3.8'

services:
  app-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdbapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:

networks:
  default:
    name: backend-network
