spring:
  application:
    name: shoppingcart
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/testdbapp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      platform: postgres
  main:
    banner-mode: "log"
  output:
    ansi:
      enabled: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1060827417895-bk1iqurld4593ocbmouegtbhqb2hl0tc.apps.googleusercontent.com
            client-secret: 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

server:
  port: 8080



logging:
  level:
    root: ERROR
    '[org.springframework.boot]': INFO
    '[org.hibernate]': WARN
    '[org.thymeleaf]': DEBUG
    '[org.springframework.security]': DEBUG'
    
debug: false
